name: Bearer SAST Scan

on:
  workflow_dispatch:  # Manual trigger

jobs:
  bearer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Bearer via Docker and print SARIF
        run: |
          echo "===== BEARER SARIF REPORT (START) ====="
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/bearer/bearer \
            scan . --format sarif
          echo "===== BEARER SARIF REPORT (END) ====="
