name: Bearer SAST Scan

on:
  workflow_dispatch:

jobs:
  bearer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Bearer CLI (fixed)
        run: |
          BEARER_VERSION=$(curl -s https://api.github.com/repos/Bearer/bearer/releases/latest | jq -r .tag_name)
          curl -L -o bearer https://github.com/Bearer/bearer/releases/download/${BEARER_VERSION}/bearer-linux-amd64
          chmod +x bearer

      - name: Run Bearer and print SARIF report
        run: |
          ./bearer scan --format sarif --output bearer_report.sarif .
          echo "===== BEARER SARIF REPORT (START) ====="
          cat bearer_report.s_
