name: Bearer SAST Scan

on:
  workflow_dispatch:  # ✅ Manual trigger

jobs:
  bearer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and run Bearer
        run: |
          curl -sSfL https://raw.githubusercontent.com/bearer/bearer/main/install.sh | sh
          ./bearer scan --format sarif --output bearer_report.sarif .

      - name: Print Bearer SARIF output
        run: |
          echo "===== BEARER SARIF REPORT (START) ====="
          cat bearer_report.sarif
          echo "===== BEARER SARIF REPORT (END) ====="
