name: ZAP DAST Scan

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP DAST inside container and extract report
        run: |
          echo "===== OWASP ZAP DAST REPORT (START) ====="

          docker run --name zap_scan ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t https://juice-shop-wo4s.onrender.com \
            -a -j -J /zap/wrk/zap_report.json || true

          docker cp zap_scan:/zap/wrk/zap_report.json ./zap_report.json || echo "No report generated"
          docker rm zap_scan > /dev/null

          cat zap_report.json || echo "Report file missing"

          echo "===== OWASP ZAP DAST REPORT (END) ====="
