name: ZAP DAST Scan (working final)

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare writable directory
        run: |
          mkdir zap-data
          chmod 777 zap-data

      - name: Run ZAP scan in Docker and write report to mounted volume
        run: |
          echo "===== OWASP ZAP DAST REPORT (START) ====="
          docker run --rm \
            -v ${{ github.workspace }}/zap-data:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t https://juice-shop-wo4s.onrender.com \
            -a -j -J /zap/wrk/zap_report.json || true

          cat zap-data/zap_report.json || echo "Report not found"
          echo "===== OWASP ZAP DAST REPORT (END) ====="
