name: ZAP DAST Scan

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP and print report (no volume mount)
        run: |
          echo "===== OWASP ZAP DAST REPORT (START) ====="
          docker run --rm ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t https://juice-shop-wo4s.onrender.com \
            -a -j -J /tmp/zap_report.json || true
          docker run --rm ghcr.io/zaproxy/zaproxy:stable cat /tmp/zap_report.json || echo "Report not generated"
          echo "===== OWASP ZAP DAST REPORT (END) ====="
