name: ZAP DAST Scan

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Create zap-data folder and placeholder file
        run: |
          mkdir -p zap-data
          touch zap-data/zap_report.json
          chmod 666 zap-data/zap_report.json  # Ensure container can write

      - name: Run ZAP and print JSON output
        run: |
          echo "===== OWASP ZAP DAST REPORT (START) ====="
          docker run --rm \
            -v ${{ github.workspace }}/zap-data:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t https://juice-shop-wo4s.onrender.com \
            -a -j -J /zap/wrk/zap_report.json || true

          cat zap-data/zap_report.json
          echo "===== OWASP ZAP DAST REPORT (END) ====="
