name: ZAP DAST Scan

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Print ZAP JSON DAST report using Docker
        run: |
          echo "===== OWASP ZAP DAST REPORT (START) ====="
          docker run --rm ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t https://juice-shop-wo4s.onrender.com \
            -a -j -r zap_report.html > zap_output.json || true
          cat zap_output.json
          echo "===== OWASP ZAP DAST REPORT (END) ====="
